export const GET_SUMMARY = 'GET_SUMMARY'
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS'
export const GET_SUMMARY_FAILURE = 'GET_SUMMARY_FAILURE'

export const GET_MOVERS = 'GET_MOVERS'
export const GET_MOVERS_SUCCESS = 'GET_MOVERS_SUCCESS'
export const GET_MOVERS_FAILURE = 'GET_MOVERS_FAILURE'

export const GET_QUOTES = 'GET_QUOTES'
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS'
export const GET_QUOTES_FAILURE = 'GET_QUOTES_FAILURE'

export const GET_AUTO_COMPLETE = 'GET_AUTO_COMPLETE'
export const GET_AUTO_COMPLETE_SUCCESS = 'GET_AUTO_COMPLETE_SUCCESS'
export const GET_AUTO_COMPLETE_FAILURE = 'GET_AUTO_COMPLETE_FAILURE'

export const GET_SPARK = 'GET_SPARK'
export const GET_SPARK_SUCCESS = 'GET_SPARK_SUCCESS'
export const GET_SPARK_FAILURE = 'GET_SPARK_FAILURE'

export const GET_EARNINGS = 'GET_EARNINGS'
export const GET_EARNINGS_SUCCESS = 'GET_EARNINGS_SUCCESS'
export const GET_EARNINGS_FAILURE = 'GET_EARNINGS_FAILURE'

export const GET_TRENDING = 'GET_TRENDING'
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS'
export const GET_TRENDING_FAILURE = 'GET_TRENDING_FAILURE'

export const GET_POPULAR = 'GET_POPULAR'
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS'
export const GET_POPULAR_FAILURE = 'GET_POPULAR_FAILURE'
